# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3672ae35565acdf0c19888c93e6bb99ebde64db20dc00512e66c589b9d471025c382b31ad8c2acb548915f12e82efb072b01d601b81a7532f01367540f629a51

test:
  secret_key_base: 2a2a1d4f6b5175916932da037b79ef23a10b3c309743bc91054b4d6eb6bf4165a68851c86886a9eb6ab08a64483fb2054cad5a02509ad457a220010a937b1dfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
